aigc-apps/sd-webui-EasyPhoto

- README_zh-CN.md
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
1、after_face_fusion_ratio概念出错，修改了预测过程，使其符合概念
2、增加随机种子的判断，-1则随机
> 修正after_face_fusion_ratio的概念，并且增加随机种子

- scripts/easyphoto_config.py
- scripts/easyphoto_infer.py
提示词prompt写错，infer才需要调用<lora:FilmVelvia3:0.65>
> fix bug in validation prompt

- scripts/preprocess.py
> update preprocess in training data

- scripts/train_kohya/train_lora.py
In the current code, if there is a problem where the preprocessed image cannot detect a face, an error will be reported and exit, which is unreasonable.
I have modified the code to accept this error and continue to the next step.
The preprocessed image will look like this:
At this point, the face detection module may sometimes fail to detect faces, resulting in an error message.
> Update error skip in model training

- README.md
- README_zh-CN.md
- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/face_process_utils.py
The color_transfer function gives a background color change, which is not good. I update a skin seg to remain the skin part of the output of color_transfer. This makes the picture more harmonious. 
After applying skin seg:
Before color_transfer:
After color_transfer:
Not applying skin seg:
Before color_transfer:
After color_transfer:
> Fix the trace of segbox in output image

- scripts/easyphoto_train.py
replace EXIF transpose method with ImageOps.exif_transpose, below is it's source code:
def exif_transpose(image, *, in_place=False):
"""
If an image has an EXIF Orientation tag, other than 1, transpose the image
accordingly, and remove the orientation data.
:param image: The image to transpose.
:param in_place: Boolean. Keyword-only argument.
If ``True``, the original image is modified in-place, and ``None`` is returned.
If ``False`` (default), a new :py:class:`~PIL.Image.Image` object is returned
with the transposition applied. If there is no transposition, a copy of the
image will be returned.
"""
image_exif = image.getexif()
orientation = image_exif.get(ExifTags.Base.Orientation)
method = {
2: Image.Transpose.FLIP_LEFT_RIGHT,
3: Image.Transpose.ROTATE_180,
4: …
> Simplify EXIF transpose

- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
Test case1: 1 face in the template and 1 user id is selected.
Test case2: 2 face in the template and 2 user id is selected.
Test case3: 2 face in the template and 1 user id is selected.
Do we need to add a description to FaceID in the accordion area?
> feature: display the FaceID of the generated images in the inference

- javascript/ui.js
- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
- scripts/preprocess.py
- scripts/sdwebui.py
- scripts/train_kohya/train_lora.py
1. Support no validation at training.
2. Fix bug when no vae in webui.
3. Give super solution buttom and no validation at training bottom.
4. Clear gpu memory in code.
The ui: 
The generated results:
> update no validation at training | fix bug in vae None | super resolution support

- .gitignore
- scripts/easyphoto_utils.py
Check the integrity of the downloaded weight file
> check weight

- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
1、支持批量上传图片进行预测；
2、将hash check用在第一次，而不是全部，全部容易速度慢；
> Support upload dir && Change hash check in first not all time

- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
> Update num of person in ui not setting

- scripts/api.py
- scripts/easyphoto_config.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
- scripts/preprocess.py
Add fast api.
post train.
```python
import base64
import json
import os
import sys
from glob import glob
import cv2
import numpy as np
import requests
def decode_image_from_base64jpeg(base64_image):
image_bytes = base64.b64decode(base64_image)
np_arr = np.frombuffer(image_bytes, np.uint8)
image = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
return image
def post(encoded_images):
datas = json.dumps({
"user_id"               : "your_user_id", 
"sd_model_checkpoint"   : "Chilloutmix-Ni-pruned-fp16-fix.safetensors",
"resolution"            : 512,
"val_and_checkpointing_steps" : 100,
"max_train_steps"       : 800,
"steps_per_photos"      : 200,
"train_batch_size"      : 1,
"gradient_accumulation_steps" : 4,
"dataloader_num_workers" : 16,
"learning_rate"         : 1e-4,
"rank"                  : 64, …
```
> Fast api Support!

- install.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
- scripts/train_kohya/train_lora.py
- scripts/train_kohya/utils/gpu_info.py
修改说明：
○ GPU： train test
■ ubuntu [done]
■ windows [ing]
○ 采样器调试试图修复眼神 [ing]
■ 改到dpm 【done】
○ start downloading weights 打印bug [done]
○ dress 不一致问题 [done]
> Beta : GPUInfo & Bugfix 

- install.py
Modelscope update will cause some bug, we now decide to fix it to 1.8.4
> Fix modelscope update bug

- install.py
- scripts/train_kohya/utils/gpu_info.py
ticker bug when time < 10, ticker will = 0 ,which cause a plot bug.
1. asset len > 10 
2. add try/except for plot
> Fix gpu ticker bug

- scripts/train_kohya/train_lora.py
fix vstack bug,when some image failed to generate normal embedding.
@bubbliiiing  need test again.
> Add try except & size check for vstack of embedding

- scripts/easyphoto_train.py
- scripts/test/README.md
- scripts/test/post_infer.py
- scripts/test/post_train.py
> Add smoke test & profiling for API mode

- scripts/easyphoto_ui.py
> Add subdir model refresh

- api_test/post_infer.py
- api_test/post_train.py
- javascript/ui.js
- scripts/api.py
- scripts/easyphoto_config.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/preprocess.py
- 按钮
- 增加了是否美颜的判断逻辑
- 按钮
- 增加了是否美颜的判断逻辑
- 增加了耳环相关的负向prompt，以防止生成不好的耳环。
> Add file & Update skin retouching enable button & Modify negative prompt for earring

- README.md
This PR adds the **Contributors Section** in `README.md` file with a button to navigate at the top of the repository.
Hi @wuziheng, I've added **Contributors Section** in `README.md` file for better visibility of **Contributors**. If you consider this PR please merge it.
> 🚀 Feature: Added 'Contributors' section in 'README.md' file

- scripts/easyphoto_infer.py
construct cn unit by using dict, not class instance
> fix cn for vars cn versions

- README.md
I have noticed one small grammar mistake in **README** inside **"Introduction"** section.
" **preferably half-body photos and ..**" should be " **preferably half-body photos, and ..**"
one enhacement ->
"**If you meet some problems in the..**" **"If you encounter any problems in the..**" 
Screenshot
> Update README.md - fix one small grammar mistake and one enhancement.

- api_test/README.md
Add version for gradio at double_blind, which gradio==3.48.0 is bug free.
> Add version for gradio at double_blind

- scripts/easyphoto_infer.py
- scripts/easyphoto_utils.py
- scripts/sdwebui.py
1、Fix bug in multi people when we want to change right people.
2、Update ms models to cpu.
before to cpu:
after to cpu:
3、Def a function for reload sd model and vae.
> Fix bug in multi people when we want to change right people && Update ms models to cpu && Def a function for reload sd model and vae

- api_test/double_blind/app.py
- api_test/double_blind/style.css
PR内容:优化了可视化双盲测试，新增多会话模式
1、服务启动后可支持多人独立会话窗口测试
2、测试完成才能查看可视化数据图
3、点击刷新即代表重新测试，也代表上次测试保存的图清空
> fix double_blind with bug

- scripts/easyphoto_infer.py
> fix the error with face shape match in SDXL

- install.py
- scripts/easyphoto_infer.py
- scripts/sdwebui.py
Fix bug in import imageio and controlnetunit havs no batch_images.
> Fix bug in lastest controlnet

- README.md
- README_zh-CN.md
Update README for Non-profit collaboration with lanrui-ai
> Lanrui readme update

- api_test/post_infer.py
- scripts/api.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
- scripts/sdwebui.py
This PR supports IP-Adapter Control in the EP inference pipeline and enables the user to upload the reference image.
UI:
> Feature: Support IP-Adapter Control

- scripts/animatediff_utils.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils.py
- scripts/sdwebui.py
1. Add version check for controllnet.
2. Add tips for Animatediff import bugs.
> Animatediff Bug fix && Controlnet version check

- scripts/api.py
Fix the incorrect RGBA format when saving images for api
> Fix the incorrect RGBA format when saving images for api

- install.py
add install for segment-anything.
> Tryon env bug fix

- scripts/sdwebui.py
> Fix seed random

- .pre-commit-config.yaml
- javascript/ui.js
- scripts/easyphoto_infer.py
- scripts/easyphoto_tryon_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils/__init__.py
- scripts/easyphoto_utils/loractl_utils.py
- scripts/sdwebui.py
1. fix switch bug in tryon.
2. fix oom problem by deleting sam model before training. Now, tryon is able to use ~8G.
> fix bug of switch and oom

- .pre-commit-config.yaml
- README.md
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
1. For UI changes such as this, click "Upload Video" to upload a video  for OpenPose control.
2. Result.
> Update Openpose control for text to video.

- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils/common_utils.py
1. add DWPose for t2v.
2. fix `add_ipa_base` in `check_files_exists_and_download`.
> add DWPose for t2v & fix download for add_ipa_base

- scripts/easyphoto_tryon_infer.py
- scripts/train_kohya/train_ddpo.py
fix bug of not found sam_predictor in tryon.
> Bug fix/tryon sam

- install.py
Add requirement for `imageio[pyav]` for the video generation.
> fix pyav env

- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils/common_utils.py
- scripts/preprocess.py
- scripts/sdwebui.py
- scripts/train_kohya/train_lora_sd_XL.py
1. Support Scene Lora with SDXL.
2. User can upload caption files with training photos to train the scene lora.
3. Use original training photos instead of cropping if `crop_ratio < 1`.
4. Add sanity check.
5. Add the logger for `easyphoto_train.py`.
> Feature: Support Scene Lora with SDXL

- scripts/easyphoto_utils/face_process_utils.py
The original code contains two cuts, which are incorrect.
> Fix bug in face skin

- scripts/api.py
> 修复推理的时候上传的图片是索引模式的时候会出现异常结果的情况

- scripts/api.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_train.py
- scripts/train_kohya/train_lora_sd_XL.py
By introducing gradient checkpointing, batch size and gradient accumulation steps can be set from (1, 4) to (4, 1) while ensuring the same gradient update steps, saving more VRAM (20G -> 14G) and training time (20min -> 15min, A100).
> Fix: batch size & gradient checkpoint

- scripts/api.py
- scripts/easyphoto_infer.py
- scripts/easyphoto_ui.py
- scripts/easyphoto_utils/animatediff_utils.py
- scripts/sdwebui.py
> Add neg prompt
